- name: create rhel9 ec2 instance
  hosts: localhost
  gather_facts: no

  tasks:
  - ansible.builtin.set_fact:
      message: "[{{ inc_number }}](https://dev198169.service-now.com/nav_to.do?uri=incident.do?sys_id={{ inc_sysid }}) - {{ url }} Certificate Expired or non existant"
  - name: Post URL to Slack channel
    community.general.slack:
      token: "{{ slack_token }}"
      channel: "#devops"
      msg: "{{ message }}"
