- name: Ensure port 80 is open
  ansible.builtin.debug:
    msg: "Port 80 is open"

- name: Ping localhost
  ansible.builtin.ping:

- name: Check if httpd service is running
  ansible.builtin.service:
    name: httpd
    state: started
  register: httpd_service_check

- name: Ensure httpd service status
  ansible.builtin.debug:
    msg: >
      httpd service is {{ 'running' if httpd_service_check.state == 'started' else 'not running' }}.

- name: Check if available memory is above 500 mb
  ansible.builtin.debug:
    msg: "Disks space for the {{ item.mount }} is {{ item.size_available / (1024 * 1024) }} MBytes"
  when: item.mount == "/"
  loop: "{{  ansible_facts['mounts'] }}"

- block:
  - name: Execute TVT test
    ansible.builtin.uri:
      url: "{{ url }}"
      method: "GET"
      return_content: true
    register: uriresults
  - ansible.builtin.debug:
      var: uriresults

  rescue:
  - ansible.builtin.debug:
      var: uriresults
  - name: set stats
    ansible.builtin.set_stats:
      data:
        error: "{{ uriresults.msg }}"
        url: "{{ url }}"
  # - ansible.builtin.include_tasks: EDA_inputs.yml
  - fail:
      msg: "TVT Test Failure"